config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'static_pages/about'
  # get 'ingredients/index'
  # get 'ingredients/show'
  # get 'measurements/show'
  # get 'people/show'
  # get 'dishes/index'
  # get 'dishes/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/dishes', to: 'dishes#index'
  # get 'dishes/:id', to: 'dishes#show', id: /\d+/

  resources :dishes, only: %i[index show]
  resources :people, only: %i[index show]
  resources :ingredients, only: %i[index show]
  resources :measurements, only: %i[index show]
  root to: 'dishes#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  paginates_per 5
  has_many :people
  has_many :measurements
  has_many :ingredients, through: :measurements

  validates :name, :description, presence: true
  validates :name, uniqueness: true

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where('name LIKE ?', "%#{search}%")
  end
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  paginates_per 20
  has_many :measurements
  has_many :dishes, through: :measurements
  validates :name, presence: true
  validates :name, uniqueness: true

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where('name LIKE ?', "%#{search}%")
  end
end

app/models/measurement.rb
# frozen_string_literal: true

class Measurement < ApplicationRecord
  paginates_per 20
  belongs_to :dish
  belongs_to :ingredient

  validates :amount, presence: true

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where('amount LIKE ?', "%#{search}%")
  end
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  paginates_per 20
  belongs_to :dish

  validates :name, presence: true

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where('name LIKE ?', "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
# frozen_string_literal: true

class DishesController < ApplicationController
  def index
    @dishes = if params[:search]
                Dish.search(params[:search]).order(:name).page params[:page]
              else
                Dish.order(:name).page params[:page]
              end
  end

  def show
    @dish = Dish.find(params[:id])
  end
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  def index
    if params[:search]
      @ingredients = Ingredient.search(params[:search]).order(:name).page params[:page]
    else
      @ingredients = Ingredient.order(:name).page params[:page]
    end
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/measurements_controller.rb
# frozen_string_literal: true

class MeasurementsController < ApplicationController
  def index
    if params[:search]
      @measurements = Measurement.search(params[:search]).order(:name).page params[:page]
    else
      @measurements = Measurement.order(:name).page params[:page]
    end
  end

  def show
    @measurement = Measurement.find(params[:id])
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  def index
    if params[:search]
      @people = Person.search(params[:search]).order(:name).page params[:page]
    else
    @people = Person.order(:name).page params[:page]
    end
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dishes/index.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/dishes">Dishes<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ingredients">Ingredients</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/people">People</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/measurements">Measurement</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="static_pages/about">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= form_tag(dishes_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search a Dish", class: "form-control mr-sm-2"%>
    <%= submit_tag 'Search', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
    </form>

  </div>
</nav>

<h1 style="text-align: center; padding: 25px 25px 25px 25px;">Dishes</h1>
<%= paginate @dishes %>
<% @dishes.each do |dish| %>
  <div class="container">
    <div class="row">
        <div class="card" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 300px;">
          <div class="card-body">
            <h5 class="card-title"><%= dish.name %></h5>
              <p class="card-text"><%= dish.description %></p>
              <%= link_to 'click here for more info', dish_path(dish)%>
          </div>
          </div>
    </div>
  </div>
<% end %>

app/views/dishes/show.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/dishes">Dishes<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ingredients">Ingredients</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/people">People</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/measurements">Measurement</a>
      </li>
        <li class="nav-item">
          <%= link_to 'About', static_pages_about_path(), class: "nav-link"%>
      </li>
    </ul>

  </div>
</nav>

<div class="card border-info mb-3" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 700px; margin-top: 50px;">
  <div class="card-body">
            <h5 class="card-title"><%= @dish.name %></h5>
            <p class="card-text"><%= @dish.description %></p>
                <div class="card text-success border-success mb-3">
                  <div class="card-header">Recipe</div>
                    <div class="card-body">
                      <% @dish.measurements.each do |measurement| %>
                            <p class="card-title"><%= link_to measurement.amount, measurement_path(measurement)%> <%= link_to measurement.ingredient.name, ingredient_path(measurement.ingredient)%></p>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="card text-danger border-danger mb-3" style="max-width: 34.1rem; margin-left: 20px;">
                  <div class="card-header">People</div>
                    <div class="card-body">
                      <% @dish.people.each do |person| %>
                          <p class="card-title"><%= link_to person.name, person_path(person)%></p>
                      <% end %>
                    </div>
                  </div>
                    <a href="/" class="card-link">&lt;&lt; Go Back</a>
                </div>

app/views/ingredients/index.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/dishes">Dishes</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/ingredients">Ingredients<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/people">People</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/measurements">Measurement</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="static_pages/about">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= form_tag(dishes_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search an Ingredient", class: "form-control mr-sm-2"%>
    <%= submit_tag 'Search', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
    </form>
  </div>
</nav>

<h1 style="text-align: center; padding: 25px 25px 25px 25px; " >Ingredients</h1>
<%= paginate @ingredients %>
<% @ingredients.each do |ingredient| %>
  <div class="container">
    <div class="row">
        <div class="card" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 300px;">
          <div class="card-body">
            <h5 class="card-title"><%= ingredient.name %></h5>
              <%= link_to 'click here for more info', ingredient_path(ingredient) %>
          </div>
          </div>
    </div>
  </div>
<% end %>

app/views/ingredients/show.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item ">
        <a class="nav-link" href="/dishes">Dishes</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/ingredients">Ingredients <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/people">People</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/measurements">Measurement</a>
      </li>
        <li class="nav-item">
        <%= link_to 'About', static_pages_about_path(), class: "nav-link"%>
      </li>
    </ul>

  </div>
</nav>

<div class="card border-info mb-3" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 700px; margin-top: 50px;">
  <div class="card-body">
            <h5 class="card-title"><%= @ingredient.name %></h5>
                <div class="card text-success border-success mb-3">
                  <div class="card-header">Measurement</div>
                    <div class="card-body">
                    <% @ingredient.measurements.each do |measurement| %>
                            <p class="card-title"><%= link_to measurement.amount, measurement_path(measurement)%> in <%= link_to measurement.dish.name, dish_path(measurement.dish)%></p>
                      <% end %>
                    </div>
                  </div>
                </div>
                    <a href="/ingredients" class="card-link">&lt;&lt; Go Back</a>
                </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>IntroToRailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/measurements/index.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/dishes">Dishes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ingredients">Ingredients</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/people">People</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="/measurements">Measurement<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="static_pages/about">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= form_tag(dishes_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search a Measurement", class: "form-control mr-sm-2"%>
    <%= submit_tag 'Search', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
    </form>
  </div>
</nav>

<h1 style="text-align: center; padding: 25px 25px 25px 25px;">Measurements</h1>
<%= paginate @measurements %>
<% @measurements.each do |measurement| %>
  <div class="container">
    <div class="row">
        <div class="card" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 300px;">
          <div class="card-body">
            <h5 class="card-title"><%= measurement.amount %></h5>
              <%= link_to 'click here for more info', measurement_path(measurement) %>
          </div>
          </div>
    </div>
  </div>
<% end %>

app/views/measurements/show.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item ">
        <a class="nav-link" href="/dishes">Dishes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ingredients">Ingredients</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/people">People</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="/measurements">Measurement<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <%= link_to 'About', static_pages_about_path(), class: "nav-link"%>
      </li>
    </ul>

  </div>
</nav>

<div class="card border-info mb-3" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 700px; margin-top: 50px;">
  <div class="card-body">
            <h5 class="card-title"><%= @measurement.amount%> of <%= link_to @measurement.ingredient.name, ingredient_path(@measurement.ingredient)%> in <%= link_to @measurement.dish.name, dish_path(@measurement.dish)%></h5>
                    <a href="/measurements" class="card-link">&lt;&lt; Go Back</a>
   </div>
 </div>

app/views/people/index.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/dishes">Dishes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ingredients">Ingredients</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/people">People<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/measurements">Measurement</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="static_pages/about">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= form_tag(dishes_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search a Person", class: "form-control mr-sm-2"%>
    <%= submit_tag 'Search', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
    </form>
  </div>
</nav>

<h1 style="text-align: center; padding: 25px 25px 25px 25px;">People</h1>
<%= paginate @people %>
<% @people.each do |person| %>
  <div class="container">
    <div class="row">
        <div class="card" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 300px;">
          <div class="card-body">
            <h5 class="card-title"><%= person.name %></h5>
              <%= link_to 'click here for more info', person_path(person) %>
          </div>
          </div>
    </div>
  </div>
<% end %>

app/views/people/show.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/dishes">Dishes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ingredients">Ingredients</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/people">People <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/measurements">Measurement</a>
      </li>
        <li class="nav-item">
        <%= link_to 'About', static_pages_about_path(), class: "nav-link"%>
      </li>
    </ul>

  </div>
</nav>

<div class="card border-danger mb-3" style="width: 600px; padding: 5px 5px 5px 5px; margin-left: 700px; margin-top: 50px;">
  <div class="card-body">
            <h5 class="card-title"><%= @person.name %></h5>
            <p class="card-text">This person loves to eat <%= link_to @person.dish.name, dish_path(@person.dish) %></p>
                    <a href="/people" class="card-link">&lt;&lt; Go Back</a>
  </div>
</div>

app/views/static_pages/about.html.erb
  <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark" style="padding: 25px 25px 25px 25px;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">It's All About Food</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/dishes">Dishes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ingredients">Ingredients</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/people">People</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/measurements">Measurement</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="static_pages/about">About <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
  <header class="bg-dark text-success" style="padding: 156px 0 100px;">
    <div class="container text-center">
      <h1>Welcome to Our Website</h1>
    </div>
  </header>

  <section id="about" style="padding: 150px 0;">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>About this page</h2>
          <p class="lead">This is for my intro to rails project. This website displays different types of dish, its ingredients, and people who love it. I am going to use Faker gem to generate fake data. There will be 4 tables in the database such as Dish, Ingredient, Measurement and Person. For the Dish table, it will have name and description. For the Ingredient table, it will only have a name. For the Measurement table, it will have the type of the measurement, references to the ingredient table and dish table. Ingredients will have many dishes and vice versa. A person will only have one favorite dish while dishes will belong to many persons.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="services" class="bg-light" style="padding: 150px 0;">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>ERD Diagram</h2>
          <img src="/images/erd.png" alt="ERD Diagram" />
          <hr/>
          <p class="lead">This the the Entity relationship diagram that I developed that specifies relationships between tables.</p>
        </div>
      </div>
    </div>
  </section>

  <section id="contact" style="padding: 150px 0;">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Contact us</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
        </div>
      </div>
    </div>
  </section>